# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.masculine_token.root] run return 0
execute at @s on passengers run rotate @s ~ ~